hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_CONFIG_HOME", "/home/sanan/.config")
hl.env("XDG_MENU_PREFIX", "arch-")
hl.env("HYPRCURSOR_SIZE", 25)
hl.env("HYPRCURSOR_THEME", "elementary")
hl.env("HYPRSHOT_DIR", "/home/sanan/.config/Pictures/screenshots")
hl.env("XKB_DEFAULT_LAYOUT", "us")

hl.env("CLUTTER_BACKEND", "wayland")
hl.env("GDK_BACKEND", "wayland,x11,*")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("SDL_VIDEODRIVER", "wayland")
